# Generated by Django 4.2.7 on 2024-01-01 00:00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0001_initial'),
        ('payments', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('html_template', models.TextField(verbose_name='HTML Template')),
                ('css_styles', models.TextField(blank=True, verbose_name='CSS Styles')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('company_address', models.TextField(verbose_name='Company Address')),
                ('company_phone', models.CharField(max_length=20, verbose_name='Company Phone')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Company Email')),
                ('company_website', models.URLField(blank=True, verbose_name='Company Website')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='invoice_templates/logos/', verbose_name='Company Logo')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10, verbose_name='Invoice Prefix')),
                ('show_tax', models.BooleanField(default=True, verbose_name='Show Tax')),
                ('show_discount', models.BooleanField(default=True, verbose_name='Show Discount')),
                ('show_terms', models.BooleanField(default=True, verbose_name='Show Terms')),
                ('show_payment_info', models.BooleanField(default=True, verbose_name='Show Payment Info')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('invoice_type', models.CharField(choices=[('RENTAL', 'Rental Invoice'), ('DEPOSIT', 'Security Deposit Invoice'), ('LATE_FEE', 'Late Fee Invoice'), ('DAMAGE_FEE', 'Damage Fee Invoice'), ('ADJUSTMENT', 'Adjustment Invoice'), ('REFUND', 'Refund Invoice')], max_length=20, verbose_name='Invoice Type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Invoice Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount Paid')),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance Due')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='Currency')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Terms and Conditions')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdfs/', verbose_name='PDF File')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF Generated At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Viewed At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='payments.payment', verbose_name='Payment')),
                ('rental_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rentals.rentalorder', verbose_name='Rental Order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='invoices_invoice_invoice__idx'), models.Index(fields=['customer', 'status'], name='invoices_invoice_customer_idx'), models.Index(fields=['invoice_date', 'due_date'], name='invoices_invoice_invoice__idx'), models.Index(fields=['status', 'due_date'], name='invoices_invoice_status__idx'), models.Index(fields=['rental_order'], name='invoices_invoice_rental__idx'), models.Index(fields=['payment'], name='invoices_invoice_payment_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Duration')),
                ('rate_type', models.CharField(blank=True, max_length=50, verbose_name='Rate Type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['invoice', 'created_at'],
            },
        ),
    ]
