# Generated by Django 5.0.6 on 2025-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_middle_name_user_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("CUSTOMER", "Customer"),
                    ("DELIVERY_PARTNER", "Delivery Partner"),
                    ("STAFF", "Staff"),
                    ("MANAGER", "Manager"),
                    ("ADMIN", "Administrator"),
                    ("SUPER_ADMIN", "Super Administrator"),
                ],
                default="USER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
