# Generated by Django 5.2.5 on 2025-08-12 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.productcategory",
                verbose_name="Parent Category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.productcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productmaintenance",
            name="assigned_technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_maintenance",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Technician",
            ),
        ),
        migrations.AddField(
            model_name="productmaintenance",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_records",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productpricing",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_rules",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(fields=["name"], name="products_pr_name_863729_idx"),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["parent"], name="products_pr_parent__84d628_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["is_featured"], name="products_pr_is_feat_26635f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["owner"], name="products_pr_owner_i_dfa922_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="products_pr_categor_75eeb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_rentable", "status"], name="products_pr_is_rent_535322_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "is_popular"],
                name="products_pr_is_feat_b2686d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["admin_approved"], name="products_pr_admin_a_01ef98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="products_pr_product_1b7905_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmaintenance",
            index=models.Index(
                fields=["product", "status"], name="products_pr_product_11ea39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmaintenance",
            index=models.Index(
                fields=["scheduled_date"], name="products_pr_schedul_e74e0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmaintenance",
            index=models.Index(
                fields=["assigned_technician"], name="products_pr_assigne_133ed2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmaintenance",
            index=models.Index(fields=["status"], name="products_pr_status_7d0ea3_idx"),
        ),
        migrations.AddIndex(
            model_name="productpricing",
            index=models.Index(
                fields=["product", "customer_type"],
                name="products_pr_product_3b07e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productpricing",
            index=models.Index(
                fields=["valid_from", "valid_to"], name="products_pr_valid_f_6d3047_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productpricing",
            index=models.Index(
                fields=["priority"], name="products_pr_priorit_7624d5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productpricing",
            unique_together={("product", "customer_type", "duration_type", "priority")},
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "rating"], name="products_pr_product_739017_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["user", "created_at"], name="products_pr_user_id_f49ca3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["is_approved"], name="products_pr_is_appr_790eda_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "user")},
        ),
    ]
