# Generated by Django 5.2.5 on 2025-08-11 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_pr_categor_75eeb5_idx_products_pr_categor_04fa16_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_75eeb5_idx',
            old_name='products_pr_categor_04fa16_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='Category'),
        ),
    ]
