# Generated by Django 5.2.5 on 2025-08-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_products_pr_categor_04fa16_idx_products_pr_categor_75eeb5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='product_images/', verbose_name='Main Image'),
        ),
    ]
