# Generated by Django 5.2.5 on 2025-08-12 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalorder",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_orders_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_schedule",
                to="payments.rentalorder",
            ),
        ),
        migrations.AddField(
            model_name="paymentnotification",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="payments.rentalorder",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.rentalorder",
            ),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="payments.rentalorder",
            ),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_payments",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalorder",
            index=models.Index(
                fields=["customer", "status"], name="payments_re_custome_776425_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalorder",
            index=models.Index(
                fields=["order_number"], name="payments_re_order_n_2c289a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalorder",
            index=models.Index(
                fields=["rental_start_date", "rental_end_date"],
                name="payments_re_rental__70f81c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentschedule",
            index=models.Index(
                fields=["order", "due_date"], name="payments_pa_order_i_5c7e3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentschedule",
            index=models.Index(
                fields=["is_paid"], name="payments_pa_is_paid_07ebb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentnotification",
            index=models.Index(
                fields=["order", "notification_type"],
                name="payments_pa_order_i_5d0ce6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentnotification",
            index=models.Index(
                fields=["is_sent", "scheduled_for"],
                name="payments_pa_is_sent_13bfb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "payment_type"], name="payments_pa_order_i_1d1017_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_id"], name="payments_pa_payment_6c9e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway_transaction_id"], name="payments_pa_gateway_2a3159_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
        ),
        migrations.AddIndex(
            model_name="rentalorderitem",
            index=models.Index(
                fields=["order", "product"], name="payments_re_order_i_3b0272_idx"
            ),
        ),
    ]
