# Generated by Django 5.2.5 on 2025-08-12 04:58

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliverySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("DELIVERY", "Delivery"),
                            ("PICKUP", "Pickup"),
                            ("SETUP", "Setup"),
                            ("RETURN", "Return"),
                        ],
                        max_length=20,
                        verbose_name="Delivery Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("DELAYED", "Delayed"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("scheduled_date", models.DateTimeField(verbose_name="Scheduled Date")),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Estimated Duration (minutes)"
                    ),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual Start Time"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual End Time"
                    ),
                ),
                ("address", models.TextField(verbose_name="Delivery Address")),
                (
                    "contact_person",
                    models.CharField(max_length=200, verbose_name="Contact Person"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Contact Phone"),
                ),
                (
                    "special_instructions",
                    models.TextField(blank=True, verbose_name="Special Instructions"),
                ),
                (
                    "driver_notes",
                    models.TextField(blank=True, verbose_name="Driver Notes"),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Vehicle Number"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Vehicle Type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Schedule",
                "verbose_name_plural": "Delivery Schedules",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price Per Unit"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit * quantity",
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation Item",
                "verbose_name_plural": "Quotation Items",
            },
        ),
        migrations.CreateModel(
            name="RentalOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Order Number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("PREPARING", "Preparing"),
                            ("READY_FOR_PICKUP", "Ready for Pickup"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial Payment"),
                            ("PAID", "Fully Paid"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Payment Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                (
                    "actual_start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual Start Date"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual End Date"
                    ),
                ),
                ("pickup_location", models.TextField(verbose_name="Pickup Location")),
                ("return_location", models.TextField(verbose_name="Return Location")),
                (
                    "delivery_required",
                    models.BooleanField(
                        default=False, verbose_name="Delivery Required"
                    ),
                ),
                (
                    "setup_required",
                    models.BooleanField(default=False, verbose_name="Setup Required"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Delivery Fee",
                    ),
                ),
                (
                    "setup_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Setup Fee",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Amount Paid",
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Balance Due",
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Security Deposit",
                    ),
                ),
                (
                    "security_deposit_paid",
                    models.BooleanField(
                        default=False, verbose_name="Security Deposit Paid"
                    ),
                ),
                (
                    "security_deposit_refunded",
                    models.BooleanField(
                        default=False, verbose_name="Security Deposit Refunded"
                    ),
                ),
                (
                    "late_return_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Late Return Fee",
                    ),
                ),
                (
                    "late_return_fee_paid",
                    models.BooleanField(
                        default=False, verbose_name="Late Return Fee Paid"
                    ),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(default=False, verbose_name="Terms Accepted"),
                ),
                (
                    "terms_accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terms Accepted At"
                    ),
                ),
                (
                    "customer_signature",
                    models.TextField(blank=True, verbose_name="Customer Signature"),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="Customer Notes"),
                ),
                (
                    "staff_notes",
                    models.TextField(blank=True, verbose_name="Staff Notes"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed At"
                    ),
                ),
                (
                    "prepared_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prepared At"
                    ),
                ),
                (
                    "picked_up_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Picked Up At"
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Returned At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental Order",
                "verbose_name_plural": "Rental Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Price"
                    ),
                ),
                (
                    "setup_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Setup Fee",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Delivery Fee",
                    ),
                ),
                (
                    "condition_at_pickup",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        max_length=20,
                        verbose_name="Condition at Pickup",
                    ),
                ),
                (
                    "condition_at_return",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        max_length=20,
                        verbose_name="Condition at Return",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "ordering": ["order", "product"],
            },
        ),
        migrations.CreateModel(
            name="RentalQuotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "quotation_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Quotation Number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent to Customer"),
                            ("REVIEWED", "Reviewed by Customer"),
                            ("CONFIRMED", "Confirmed by Customer"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                ("pickup_location", models.TextField(verbose_name="Pickup Location")),
                ("return_location", models.TextField(verbose_name="Return Location")),
                (
                    "delivery_required",
                    models.BooleanField(
                        default=False, verbose_name="Delivery Required"
                    ),
                ),
                (
                    "setup_required",
                    models.BooleanField(default=False, verbose_name="Setup Required"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, verbose_name="Terms and Conditions"),
                ),
                (
                    "special_instructions",
                    models.TextField(blank=True, verbose_name="Special Instructions"),
                ),
                (
                    "cancellation_policy",
                    models.TextField(blank=True, verbose_name="Cancellation Policy"),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Valid Until")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental Quotation",
                "verbose_name_plural": "Rental Quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalQuotationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Price"
                    ),
                ),
                (
                    "setup_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Setup Fee",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Delivery Fee",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Quotation Item",
                "verbose_name_plural": "Quotation Items",
                "ordering": ["quotation", "product"],
            },
        ),
    ]
