# Generated by Django 5.2.5 on 2025-08-12 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_initial"),
        ("rentals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryschedule",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_deliveries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Driver",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_items",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Staff",
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="deliveryschedule",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_schedules",
                to="rentals.rentalorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_items",
                to="rentals.rentalorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="rentalorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="rentalquotation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_quotations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="rentalquotationitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="rentalquotationitem",
            name="quotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="rentals.rentalquotation",
                verbose_name="Quotation",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalorder",
            index=models.Index(
                fields=["customer", "status"], name="rentals_ren_custome_1a36fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalorder",
            index=models.Index(
                fields=["order_number"], name="rentals_ren_order_n_4051af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalorder",
            index=models.Index(
                fields=["start_date", "end_date"], name="rentals_ren_start_d_acfe5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalorder",
            index=models.Index(
                fields=["status", "payment_status"],
                name="rentals_ren_status_ea39c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryschedule",
            index=models.Index(
                fields=["order", "delivery_type"], name="rentals_del_order_i_458657_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryschedule",
            index=models.Index(
                fields=["scheduled_date", "status"],
                name="rentals_del_schedul_8d6020_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryschedule",
            index=models.Index(
                fields=["assigned_driver"], name="rentals_del_assigne_2a8225_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rentalorderitem",
            unique_together={("order", "product")},
        ),
        migrations.AddIndex(
            model_name="rentalquotation",
            index=models.Index(
                fields=["customer", "status"], name="rentals_ren_custome_a33ec2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalquotation",
            index=models.Index(
                fields=["quotation_number"], name="rentals_ren_quotati_4ce91d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalquotation",
            index=models.Index(
                fields=["start_date", "end_date"], name="rentals_ren_start_d_998c2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalquotation",
            index=models.Index(
                fields=["status", "valid_until"], name="rentals_ren_status_cfff5a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rentalquotationitem",
            unique_together={("quotation", "product")},
        ),
    ]
