# Generated by Django 5.2.5 on 2025-08-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("USER_REGISTRATION", "User Registration"),
                            ("RENTAL_CONFIRMATION", "Rental Confirmation"),
                            ("PRODUCT_DELIVERY", "Product Delivery"),
                            ("PRODUCT_RETURN", "Product Return"),
                            ("RENTAL_REMINDER", "Rental Reminder"),
                            ("PAYMENT_SUCCESS", "Payment Success"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("DELIVERY_UPDATE", "Delivery Update"),
                            ("WELCOME_EMAIL", "Welcome Email"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("OTP_VERIFICATION", "OTP Verification"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("PUSH", "Push")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("USER_REGISTRATION", "User Registration"),
                            ("RENTAL_CONFIRMATION", "Rental Confirmation"),
                            ("PRODUCT_DELIVERY", "Product Delivery"),
                            ("PRODUCT_RETURN", "Product Return"),
                            ("RENTAL_REMINDER", "Rental Reminder"),
                            ("PAYMENT_SUCCESS", "Payment Success"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("DELIVERY_UPDATE", "Delivery Update"),
                            ("WELCOME_EMAIL", "Welcome Email"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("OTP_VERIFICATION", "OTP Verification"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("recipient", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("html_content", models.TextField(blank=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                (
                    "related_object_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
