# Generated by Django 5.2.5 on 2025-08-11 18:20

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("USER_REGISTRATION", "User Registration"),
                            ("RENTAL_CONFIRMATION", "Rental Confirmation"),
                            ("PRODUCT_DELIVERY", "Product Delivery"),
                            ("PRODUCT_RETURN", "Product Return"),
                            ("RENTAL_REMINDER", "Rental Reminder"),
                            ("PAYMENT_SUCCESS", "Payment Success"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("DELIVERY_UPDATE", "Delivery Update"),
                            ("WELCOME_EMAIL", "Welcome Email"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("OTP_VERIFICATION", "OTP Verification"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("USER_REGISTRATION", "User Registration"),
                    ("RENTAL_CONFIRMATION", "Rental Confirmation"),
                    ("PRODUCT_DELIVERY", "Product Delivery"),
                    ("PRODUCT_RETURN", "Product Return"),
                    ("RENTAL_REMINDER", "Rental Reminder"),
                    ("PAYMENT_SUCCESS", "Payment Success"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("DELIVERY_UPDATE", "Delivery Update"),
                    ("WELCOME_EMAIL", "Welcome Email"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("OTP_VERIFICATION", "OTP Verification"),
                    ("SYSTEM", "System"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="html_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_object_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_object_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="notification",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="subject",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("PUSH", "Push")],
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "status"], name="notificatio_user_id_7088ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["category", "status"], name="notificatio_categor_fa23e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_46ad24_idx"
            ),
        ),
    ]
