# Generated by Django 5.0.6 on 2025-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_emailtemplate_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_object_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
