# Generated by Django 5.0.6 on 2025-08-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_related_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_object_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
