# Generated by Django 5.2.5 on 2025-08-12 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery_partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryjob",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_partner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliveryjob",
            name="assigned_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_jobs",
                to="delivery_partners.deliverypartner",
            ),
        ),
        migrations.AddField(
            model_name="deliverytracking",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_events",
                to="delivery_partners.deliveryjob",
            ),
        ),
        migrations.AddField(
            model_name="deliverytracking",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_events",
                to="delivery_partners.deliverypartner",
            ),
        ),
        migrations.AddField(
            model_name="jobassignment",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="delivery_partners.deliveryjob",
            ),
        ),
        migrations.AddField(
            model_name="jobassignment",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_assignments",
                to="delivery_partners.deliverypartner",
            ),
        ),
        migrations.AddField(
            model_name="partnerearnings",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_earnings",
                to="delivery_partners.deliveryjob",
            ),
        ),
        migrations.AddField(
            model_name="partnerearnings",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earnings",
                to="delivery_partners.deliverypartner",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverypartner",
            index=models.Index(
                fields=["status", "is_available"], name="delivery_pa_status_c34b0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverypartner",
            index=models.Index(
                fields=["partner_code"], name="delivery_pa_partner_f518b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverypartner",
            index=models.Index(
                fields=["phone_number"], name="delivery_pa_phone_n_b5bcc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverypartner",
            index=models.Index(
                fields=["vehicle_number"], name="delivery_pa_vehicle_77a3db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverypartner",
            index=models.Index(
                fields=["city", "state"], name="delivery_pa_city_503de5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverypartner",
            index=models.Index(fields=["rating"], name="delivery_pa_rating_e69fc2_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverypartner",
            index=models.Index(
                fields=["current_latitude", "current_longitude"],
                name="delivery_pa_current_4653f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryjob",
            index=models.Index(fields=["job_id"], name="delivery_pa_job_id_7590ba_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryjob",
            index=models.Index(
                fields=["status", "priority"], name="delivery_pa_status_f5530b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryjob",
            index=models.Index(
                fields=["customer"], name="delivery_pa_custome_4ec02f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryjob",
            index=models.Index(
                fields=["assigned_partner"], name="delivery_pa_assigne_aaf4be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryjob",
            index=models.Index(
                fields=["pickup_date", "delivery_date"],
                name="delivery_pa_pickup__c6ff5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryjob",
            index=models.Index(
                fields=["pickup_pincode", "delivery_pincode"],
                name="delivery_pa_pickup__bf6dd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryjob",
            index=models.Index(
                fields=["tracking_number"], name="delivery_pa_trackin_6c45f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryjob",
            index=models.Index(
                fields=["is_urgent", "priority"], name="delivery_pa_is_urge_542cd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytracking",
            index=models.Index(
                fields=["job", "event_time"], name="delivery_pa_job_id_e22a38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytracking",
            index=models.Index(
                fields=["partner", "event_time"], name="delivery_pa_partner_e6f94a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytracking",
            index=models.Index(
                fields=["event_type", "event_time"],
                name="delivery_pa_event_t_276ba3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobassignment",
            index=models.Index(
                fields=["status", "expires_at"], name="delivery_pa_status_74b2f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobassignment",
            index=models.Index(
                fields=["job", "partner"], name="delivery_pa_job_id_685017_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobassignment",
            index=models.Index(
                fields=["assigned_at"], name="delivery_pa_assigne_3d411f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobassignment",
            unique_together={("job", "partner")},
        ),
        migrations.AddIndex(
            model_name="partnerearnings",
            index=models.Index(
                fields=["partner", "status"], name="delivery_pa_partner_8f3afc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerearnings",
            index=models.Index(fields=["job"], name="delivery_pa_job_id_a71781_idx"),
        ),
        migrations.AddIndex(
            model_name="partnerearnings",
            index=models.Index(
                fields=["earning_type", "earned_date"],
                name="delivery_pa_earning_02cba7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnerearnings",
            index=models.Index(
                fields=["status", "earned_date"], name="delivery_pa_status_3f087f_idx"
            ),
        ),
    ]
